// <auto-generated />
using System;
using INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260205122226_AddPerformanceReportAndRenameAgentId")]
    partial class AddPerformanceReportAndRenameAgentId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RelatedCallId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RelatedCallId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.PerformanceReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("AvgHandlingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("ReportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("SalesConversionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TicketsResolved")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("PerformanceReports");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriptionMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 22, 25, 13, DateTimeKind.Utc).AddTicks(1029),
                            Description = "Premium 100% cotton t-shirt in various colors",
                            IsActive = true,
                            IsSubscription = false,
                            MinStockLevel = 5,
                            Name = "Classic Cotton T-Shirt",
                            Price = 29.99m,
                            SKU = "APP-001",
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 2,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 22, 25, 13, DateTimeKind.Utc).AddTicks(1032),
                            Description = "Comfortable slim fit denim jeans",
                            IsActive = true,
                            IsSubscription = false,
                            MinStockLevel = 5,
                            Name = "Slim Fit Jeans",
                            Price = 59.99m,
                            SKU = "APP-002",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 22, 25, 13, DateTimeKind.Utc).AddTicks(1035),
                            Description = "Insulated winter jacket for cold weather",
                            IsActive = true,
                            IsSubscription = false,
                            MinStockLevel = 5,
                            Name = "Winter Parka Jacket",
                            Price = 129.99m,
                            SKU = "APP-003",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 4,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 22, 25, 13, DateTimeKind.Utc).AddTicks(1038),
                            Description = "Soft fleece hoodie with kangaroo pocket",
                            IsActive = true,
                            IsSubscription = false,
                            MinStockLevel = 5,
                            Name = "Pullover Hoodie",
                            Price = 49.99m,
                            SKU = "APP-004",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 5,
                            Category = 6,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 22, 25, 13, DateTimeKind.Utc).AddTicks(1041),
                            Description = "Versatile chino pants for work or casual wear",
                            IsActive = true,
                            IsSubscription = false,
                            MinStockLevel = 5,
                            Name = "Casual Chinos",
                            Price = 54.99m,
                            SKU = "APP-005",
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByAgentId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedCallId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId");

                    b.HasIndex("CreatedByAgentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RelatedCallId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 5, 12, 22, 25, 13, DateTimeKind.Utc).AddTicks(579),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$V1nE8ud6nd6fpVrHvENU1u5D92QVcqWNYqlUivFPViFVqfGP81Xp.",
                            Phone = "0000000000",
                            Role = 3
                        });
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Call", b =>
                {
                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", "Agent")
                        .WithMany("Calls")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Customer", "Customer")
                        .WithMany("Calls")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Order", b =>
                {
                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", "Agent")
                        .WithMany("Orders")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Call", "RelatedCall")
                        .WithMany()
                        .HasForeignKey("RelatedCallId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agent");

                    b.Navigation("Customer");

                    b.Navigation("RelatedCall");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.OrderDetail", b =>
                {
                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.PerformanceReport", b =>
                {
                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", "Agent")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Ticket", b =>
                {
                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", "AssignedAgent")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", "CreatedByAgent")
                        .WithMany()
                        .HasForeignKey("CreatedByAgentId");

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Call", "RelatedCall")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("RelatedCallId");

                    b.Navigation("AssignedAgent");

                    b.Navigation("CreatedByAgent");

                    b.Navigation("Customer");

                    b.Navigation("RelatedCall");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.TicketComment", b =>
                {
                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Call", b =>
                {
                    b.Navigation("CreatedTickets");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Orders");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.Ticket", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("INTEGRATE_SUPPORT_SALES_MANAGEMENT_SYSTEM.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Calls");

                    b.Navigation("Orders");

                    b.Navigation("PerformanceReports");
                });
#pragma warning restore 612, 618
        }
    }
}
