<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorEnableCompression>false</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.22" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
  </ItemGroup>

  <Target Name="BuildTailwindCss" BeforeTargets="Build">
    <Exec Command="npm run build-css-prod" WorkingDirectory="$(ProjectDir)" ContinueOnError="false" />
  </Target>


</Project>
